export const MITRE_TACTICS = {
  reconnaissance: {
    id: 'TA0043',
    name: 'Reconnaissance',
    description: 'Gathering information to plan future adversary operations',
  },
  resource_development: {
    id: 'TA0042',
    name: 'Resource Development',
    description: 'Establishing resources to support operations',
  },
  initial_access: {
    id: 'TA0001',
    name: 'Initial Access',
    description: 'Trying to get into your network',
  },
  execution: {
    id: 'TA0002',
    name: 'Execution',
    description: 'Trying to run malicious code',
  },
  persistence: {
    id: 'TA0003',
    name: 'Persistence',
    description: 'Trying to maintain their foothold',
  },
  privilege_escalation: {
    id: 'TA0004',
    name: 'Privilege Escalation',
    description: 'Trying to gain higher-level permissions',
  },
  defense_evasion: {
    id: 'TA0005',
    name: 'Defense Evasion',
    description: 'Trying to avoid being detected',
  },
  credential_access: {
    id: 'TA0006',
    name: 'Credential Access',
    description: 'Trying to steal account credentials',
  },
  discovery: {
    id: 'TA0007',
    name: 'Discovery',
    description: 'Trying to figure out your environment',
  },
  lateral_movement: {
    id: 'TA0008',
    name: 'Lateral Movement',
    description: 'Trying to move through your environment',
  },
  collection: {
    id: 'TA0009',
    name: 'Collection',
    description: 'Gathering data of interest to their goal',
  },
  command_and_control: {
    id: 'TA0011',
    name: 'Command and Control',
    description: 'Communicating with compromised systems',
  },
  exfiltration: {
    id: 'TA0010',
    name: 'Exfiltration',
    description: 'Trying to steal data',
  },
  impact: {
    id: 'TA0040',
    name: 'Impact',
    description: 'Trying to manipulate, interrupt, or destroy systems',
  },
} as const;

export type MitreTacticId = keyof typeof MITRE_TACTICS;
export type MitreTactic = (typeof MITRE_TACTICS)[MitreTacticId];

export const MITRE_TACTIC_IDS: Record<string, string> = {
  TA0043: 'Reconnaissance',
  TA0042: 'Resource Development',
  TA0001: 'Initial Access',
  TA0002: 'Execution',
  TA0003: 'Persistence',
  TA0004: 'Privilege Escalation',
  TA0005: 'Defense Evasion',
  TA0006: 'Credential Access',
  TA0007: 'Discovery',
  TA0008: 'Lateral Movement',
  TA0009: 'Collection',
  TA0011: 'Command and Control',
  TA0010: 'Exfiltration',
  TA0040: 'Impact',
};

export const MITRE_TECHNIQUES = {
  T1190: { name: 'Exploit Public-Facing Application', tactic: 'initial_access' },
  T1133: { name: 'External Remote Services', tactic: 'initial_access' },
  T1200: { name: 'Hardware Additions', tactic: 'initial_access' },
  T1566: { name: 'Phishing', tactic: 'initial_access' },
  'T1566.001': { name: 'Spearphishing Attachment', tactic: 'initial_access' },
  'T1566.002': { name: 'Spearphishing Link', tactic: 'initial_access' },
  T1091: { name: 'Replication Through Removable Media', tactic: 'initial_access' },
  T1195: { name: 'Supply Chain Compromise', tactic: 'initial_access' },
  T1199: { name: 'Trusted Relationship', tactic: 'initial_access' },
  T1078: { name: 'Valid Accounts', tactic: 'initial_access' },
  T1059: { name: 'Command and Scripting Interpreter', tactic: 'execution' },
  'T1059.001': { name: 'PowerShell', tactic: 'execution' },
  'T1059.003': { name: 'Windows Command Shell', tactic: 'execution' },
  'T1059.004': { name: 'Unix Shell', tactic: 'execution' },
  'T1059.005': { name: 'Visual Basic', tactic: 'execution' },
  'T1059.006': { name: 'Python', tactic: 'execution' },
  'T1059.007': { name: 'JavaScript', tactic: 'execution' },
  T1203: { name: 'Exploitation for Client Execution', tactic: 'execution' },
  T1047: { name: 'Windows Management Instrumentation', tactic: 'execution' },
  T1053: { name: 'Scheduled Task/Job', tactic: 'execution' },
  T1204: { name: 'User Execution', tactic: 'execution' },
  T1098: { name: 'Account Manipulation', tactic: 'persistence' },
  T1547: { name: 'Boot or Logon Autostart Execution', tactic: 'persistence' },
  'T1547.001': { name: 'Registry Run Keys / Startup Folder', tactic: 'persistence' },
  T1136: { name: 'Create Account', tactic: 'persistence' },
  T1543: { name: 'Create or Modify System Process', tactic: 'persistence' },
  T1546: { name: 'Event Triggered Execution', tactic: 'persistence' },
  T1574: { name: 'Hijack Execution Flow', tactic: 'persistence' },
  T1548: { name: 'Abuse Elevation Control Mechanism', tactic: 'privilege_escalation' },
  'T1548.002': { name: 'Bypass User Account Control', tactic: 'privilege_escalation' },
  T1134: { name: 'Access Token Manipulation', tactic: 'privilege_escalation' },
  T1068: { name: 'Exploitation for Privilege Escalation', tactic: 'privilege_escalation' },
  T1055: { name: 'Process Injection', tactic: 'privilege_escalation' },
  T1070: { name: 'Indicator Removal', tactic: 'defense_evasion' },
  'T1070.001': { name: 'Clear Windows Event Logs', tactic: 'defense_evasion' },
  'T1070.004': { name: 'File Deletion', tactic: 'defense_evasion' },
  T1036: { name: 'Masquerading', tactic: 'defense_evasion' },
  T1027: { name: 'Obfuscated Files or Information', tactic: 'defense_evasion' },
  T1218: { name: 'System Binary Proxy Execution', tactic: 'defense_evasion' },
  T1562: { name: 'Impair Defenses', tactic: 'defense_evasion' },
  'T1562.001': { name: 'Disable or Modify Tools', tactic: 'defense_evasion' },
  T1110: { name: 'Brute Force', tactic: 'credential_access' },
  'T1110.001': { name: 'Password Guessing', tactic: 'credential_access' },
  'T1110.002': { name: 'Password Cracking', tactic: 'credential_access' },
  'T1110.003': { name: 'Password Spraying', tactic: 'credential_access' },
  'T1110.004': { name: 'Credential Stuffing', tactic: 'credential_access' },
  T1003: { name: 'OS Credential Dumping', tactic: 'credential_access' },
  'T1003.001': { name: 'LSASS Memory', tactic: 'credential_access' },
  T1555: { name: 'Credentials from Password Stores', tactic: 'credential_access' },
  T1056: { name: 'Input Capture', tactic: 'credential_access' },
  T1539: { name: 'Steal Web Session Cookie', tactic: 'credential_access' },
  T1087: { name: 'Account Discovery', tactic: 'discovery' },
  T1083: { name: 'File and Directory Discovery', tactic: 'discovery' },
  T1046: { name: 'Network Service Discovery', tactic: 'discovery' },
  T1135: { name: 'Network Share Discovery', tactic: 'discovery' },
  T1057: { name: 'Process Discovery', tactic: 'discovery' },
  T1018: { name: 'Remote System Discovery', tactic: 'discovery' },
  T1082: { name: 'System Information Discovery', tactic: 'discovery' },
  T1016: { name: 'System Network Configuration Discovery', tactic: 'discovery' },
  T1021: { name: 'Remote Services', tactic: 'lateral_movement' },
  'T1021.001': { name: 'Remote Desktop Protocol', tactic: 'lateral_movement' },
  'T1021.002': { name: 'SMB/Windows Admin Shares', tactic: 'lateral_movement' },
  'T1021.004': { name: 'SSH', tactic: 'lateral_movement' },
  'T1021.006': { name: 'Windows Remote Management', tactic: 'lateral_movement' },
  T1080: { name: 'Taint Shared Content', tactic: 'lateral_movement' },
  T1550: { name: 'Use Alternate Authentication Material', tactic: 'lateral_movement' },
  'T1550.002': { name: 'Pass the Hash', tactic: 'lateral_movement' },
  'T1550.003': { name: 'Pass the Ticket', tactic: 'lateral_movement' },
  T1560: { name: 'Archive Collected Data', tactic: 'collection' },
  T1119: { name: 'Automated Collection', tactic: 'collection' },
  T1115: { name: 'Clipboard Data', tactic: 'collection' },
  T1213: { name: 'Data from Information Repositories', tactic: 'collection' },
  'T1213.003': { name: 'Code Repositories', tactic: 'collection' },
  T1005: { name: 'Data from Local System', tactic: 'collection' },
  T1039: { name: 'Data from Network Shared Drive', tactic: 'collection' },
  T1025: { name: 'Data from Removable Media', tactic: 'collection' },
  T1074: { name: 'Data Staged', tactic: 'collection' },
  T1113: { name: 'Screen Capture', tactic: 'collection' },
  T1071: { name: 'Application Layer Protocol', tactic: 'command_and_control' },
  'T1071.001': { name: 'Web Protocols', tactic: 'command_and_control' },
  'T1071.004': { name: 'DNS', tactic: 'command_and_control' },
  T1132: { name: 'Data Encoding', tactic: 'command_and_control' },
  T1001: { name: 'Data Obfuscation', tactic: 'command_and_control' },
  T1568: { name: 'Dynamic Resolution', tactic: 'command_and_control' },
  T1573: { name: 'Encrypted Channel', tactic: 'command_and_control' },
  T1008: { name: 'Fallback Channels', tactic: 'command_and_control' },
  T1105: { name: 'Ingress Tool Transfer', tactic: 'command_and_control' },
  T1104: { name: 'Multi-Stage Channels', tactic: 'command_and_control' },
  T1095: { name: 'Non-Application Layer Protocol', tactic: 'command_and_control' },
  T1571: { name: 'Non-Standard Port', tactic: 'command_and_control' },
  T1572: { name: 'Protocol Tunneling', tactic: 'command_and_control' },
  T1090: { name: 'Proxy', tactic: 'command_and_control' },
  T1219: { name: 'Remote Access Software', tactic: 'command_and_control' },
  'T1219.002': { name: 'Remote Access Tools', tactic: 'command_and_control' },
  T1020: { name: 'Automated Exfiltration', tactic: 'exfiltration' },
  T1030: { name: 'Data Transfer Size Limits', tactic: 'exfiltration' },
  T1048: { name: 'Exfiltration Over Alternative Protocol', tactic: 'exfiltration' },
  T1041: { name: 'Exfiltration Over C2 Channel', tactic: 'exfiltration' },
  T1011: { name: 'Exfiltration Over Other Network Medium', tactic: 'exfiltration' },
  T1052: { name: 'Exfiltration Over Physical Medium', tactic: 'exfiltration' },
  T1567: { name: 'Exfiltration Over Web Service', tactic: 'exfiltration' },
  T1029: { name: 'Scheduled Transfer', tactic: 'exfiltration' },
  T1531: { name: 'Account Access Removal', tactic: 'impact' },
  T1485: { name: 'Data Destruction', tactic: 'impact' },
  T1486: { name: 'Data Encrypted for Impact', tactic: 'impact' },
  T1565: { name: 'Data Manipulation', tactic: 'impact' },
  T1491: { name: 'Defacement', tactic: 'impact' },
  T1561: { name: 'Disk Wipe', tactic: 'impact' },
  T1499: { name: 'Endpoint Denial of Service', tactic: 'impact' },
  T1495: { name: 'Firmware Corruption', tactic: 'impact' },
  T1490: { name: 'Inhibit System Recovery', tactic: 'impact' },
  T1498: { name: 'Network Denial of Service', tactic: 'impact' },
  T1496: { name: 'Resource Hijacking', tactic: 'impact' },
  T1489: { name: 'Service Stop', tactic: 'impact' },
  T1529: { name: 'System Shutdown/Reboot', tactic: 'impact' },
} as const;

export type MitreTechniqueId = keyof typeof MITRE_TECHNIQUES;
export type MitreTechnique = (typeof MITRE_TECHNIQUES)[MitreTechniqueId];
